### PR TITLE
add mafft_and_snp_annotated.wdl

### PR DESCRIPTION
**Pull request by tomkinsc**
This adds a new workflow, `mafft_and_snp_annotated`, which is the same as mafft_and_snp, except it includes annotation of the vcf via snpEff. It is included as a separate workflow because snpEff may fail if the ref annotations cannot be found, its input does not match the ref provided, etc.

### CODE REVIEW

**Review by dpark01 — COMMENTED** [review]
Cool -- two thoughts,
1. what if we keep it in the main workflow and stick it in an `if` block (like the iqtree part) based on some workflow level input param?
2. or if not (and we keep it separate), don't forget to add a stub to `.dockstore.yml` or it won't show up there

**Comment by tomkinsc** [comment]
Thanks for reminding me about the `.dockstore.yml` manifest—I actually don't think I've added a workflow since dockstore integration went live.

Yeah I considered making it a toggle—what would you want the conditional to be based on? The snpEff task currently uses the accessions in the reference fasta to fetch the annotations, unless a different list of accessions is specified as an override. What if we want to run the workflow without snpEff—do we provide an empty but not null override?
Maybe we can keep it separate for now?

**Comment by tomkinsc** [comment]
I do see it: https://dockstore.org/my-workflows/github.com/broadinstitute/viral-pipelines/mafft_and_snp_annotated
Does that link work for you?

**Comment by dpark01** [comment]
Nope, I can't see it -- I wonder if dockstore is doing something interesting where it sees that your branch is owned by you and isn't showing it to me?

Let's merge it and see what happens.

**Comment by tomkinsc** [comment]
Will do. A couple things to fix first.

**Pull request merged**
