### PR TITLE
dx beast timeout

### LINKED ISSUE #116: remove dnanexus runtime limit for beast_gpu
From @pauloluniyi:

> I just got a notification that the beast run failed because it exceeded the job timeout of 20.000hrs. 
> 
> Is it possible to increase the timeout? I'm running the bayesian analyses for 200 million MCMC steps with parameters and trees sampled every 10000 generations and so it might need to run for longer than 20 hours.

### PR DESCRIPTION
**Pull request by tomkinsc**
This adds a DNAnexus runtime hint to the beast task to limit execution to 240H (an increase over the default of 20H specified in `dx-extras.json`).

This should be rebased or squashed.

Closes #116

### CODE REVIEW

**Comment by tomkinsc** [comment]
Hmm... I don't see a timeout value via `dx describe --verbose` for the task nor the workflow calling it. `dx describe` lists `"runtimeAttrs": {}`, but I don't see gpu mentioned anywhere either. When you were adding runtime attributes for the beast task, did you find a way to inspect the built entities?

**Comment by dpark01** [comment]
No... if there's a way to inspect via dx api calls that'd be awesome but I never figured it out. That one time I was banging my head over demuxing the S4 flowcells and trying to get the timeout above its default value was mostly trial and error....

If, as best as we can tell, this is okay, then maybe @pauloluniyi can [give it a try](https://platform.dnanexus.com/panx/projects/F8PQ6380xf5bK0Qk0YPjB17P/data/build/quay.io/broadinstitute/viral-pipelines-dev/2.1.0.2-59-ge6f5269-ct-dx-beast-timeout/) and let us know if it makes it past the 20hr mark this time? Also Paul, how much did 20 hours cost on this instance?

**Comment by pauloluniyi** [comment]
@dpark01 it cost 663.9138 dollars

**Comment by dpark01** [comment]
Oh wow... @pauloluniyi how fast was it running? (how many hours per million states).. there's quite an art to tuning the model to make the most efficient use of resources, especially if you're aiming for 200M states (which might cost you $6000-7000 USD)?

**Comment by pauloluniyi** [comment]
@dpark01 it was running at 1.8 hours/million states

**Comment by dpark01** [comment]
Hm ok we should discuss the model offline perhaps — I don’t think it makes sense to spend $13k USD on this particular run!

Perhaps let’s play with the same xml on GCP and see if we can do better there? Send us a link to the xml (maybe share the dnanexus project and point to the file) and we’ll give it a try.

@tomkinsc I think I’m leaning back towards a more conservative timeout by default like you were initially thinking!

**Comment by pauloluniyi** [comment]
@dpark01 i just shared the dna nexus project with you and @tomkinsc . the xml file is in .beast_xml_file

**Comment by dpark01** [comment]
@tomkinsc I just realized the reason this was so expensive was that DNAnexus assigned it an instance type that had four V100 GPUs attached--the most expensive option. The last time I had tested it out, it was assigning a more economical one by default. For this PR, can you set the dx_instance_type to mem1_ssd1_gpu2_x8 to keep it more predictable?

**Pull request merged**
