### PR TITLE
Add genbank curate

### PR DESCRIPTION
**Pull request by cmloreth**
Moved genbank_curate.wdl to viral-pipelines repo

### CODE REVIEW

**Comment by tomkinsc** [comment]
Thanks! Let's prefix the workflow name with "sarscov2_" for now (since that's what it does) until we have the ability to pass through a different viral taxid

**Comment by dpark01** [comment]
Also maybe use a verb other than "curate" (the actual Genbank curators might beg to differ about what this tool does). Maybe "ingest"? Or "ETL"?

Otherwise, excited to see this go in!

**Comment by tomkinsc** [comment]
We should also probably move the [repo](https://github.com/cmloreth/pathogen-genomics) with Dockerfile and python script to the broad org on GitHub (with build on the broad quay).

**Comment by dpark01** [comment]
can we close this in favor of #223 ?

**Comment by dpark01** [comment]
Closing in favor of #223

**Pull request closed without merging**
